
export const CHANGE_HEADER = "CHANGE_HEADER"
export const CHANGE_TABINDEX = "CHANGE_TABINDEX"
export const CHANGE_TITLE = "CHANGE_TITLE"
export const CHANGE_META = "CHANGE_META"
export const CHANGE_CHANNELID = "CHANGE_CHANNELID"
export const OPEN_LOADING = 'OPEN_LOADING'
export const CLOSE_LOADING = 'CLOSE_LOADING'
export const CHANGE_OPTIONS = 'CHANGE_OPTIONS'
export const UPDATE_SEARCH_VALUE = 'UPDATE_SEARCH_VALUE'
export const UPDATE_SEARCH_WORDS = 'UPDATE_SEARCH_WORDS'
export const CHANGE_NEEDKEEPALIVE = 'CHANGE_NEEDKEEPALIVE'
export const UPDATE_KEEP_ALIVE = 'UPDATE_KEEP_ALIVE'
